### ISSUE TITLE
How do I install Better Ruby? 

### ISSUE THREAD

**Issue by lucanioi** [fnando/better-ruby-for-sublime-text#2]
I'm sorry, it might be a stupid question. But I can't find 'Better Ruby' in the list of available packages from sublime. Cloning the repo into Application Support/Sublime Text 3/Packages/Ruby or Application Support/Sublime Text 3/Packages/ doesn't work either.

**Comment by Erquint** [comment]
There's an installation instructions section in the main README.MD but frankly it's a clusterduck. 

@fnando
While most, almost all, packages available for Sublime Text allow for quick installation from the main repository, subscribing to a 3rd-party repository and installing the package is the most a package developer can usually ask of the user.

Asking users on top of that to manually disable built-in packages, install other ones and paste configurations into them is leaving far too much opportunity for user error in the process.

It's too convoluted. Use requirements and overrides in the package itself instead.

**Comment by fnando** [comment]
There isn't much to be done. I follow this approach because one cannot override default languages (at least that's my recollection).

**Comment by fnando** [comment]
Also, the idea behind having a custom repository is because adding packages to package control is cumbersome, and I like having control over repos, branches, and alike, without having to issue pull requests against the packagecontrol's main repo.

**Comment by Erquint** [comment]
My point was that "subscribing to a 3rd-party repository" is still acceptable although on the fringe. Anything __past__ that is asking for trouble.
